name = "rnf-location-service"
main = "./src/index.ts"

workers_dev = false
compatibility_date = "2021-09-18"

route = { pattern = "api.routenotfound.com", custom_domain = true }

[vars]
GMAPS_API_ENDPOINT = "https://maps.googleapis.com/maps/api/geocode/json"

[triggers]
crons = ["0 * * * *"]

[env.dev]
route = { pattern = "api.dev.routenotfound.com", custom_domain = true }

[env.dev.triggers]
crons = ["0 * * * *"]

[env.dev.vars]
GMAPS_API_ENDPOINT = "https://maps.googleapis.com/maps/api/geocode/json"

# Define secrets in each env:
# API_ADMIN_PASS <-- These two are what the admin app should use
# API_ADMIN_USER <-- ^
# DB_ENDPOINT  <-- PostgREST endpoint URL
# DB_ADMIN_JWT <-- This is how this script connects to PostgREST
# GMAPS_API_KEY
